env:
  browser: true
  es2020: true
extends:
  - eslint:recommended
  - plugin:vue/vue3-essential
parserOptions:
  ecmaVersion: es2021
  sourceType: module
plugins:
  - vue
rules: {}
eslint.validate: 
  -  "javascript"
  -  "javascriptreact"
  -  "vue"
